
export const Product_face = [
	{
		id: 1,
		product_name: "xe tang",
		price: 100000,
		sale: "12%",
		imager: "product-1.png",
		top_rated: 1,
		quantity: 1,
	},
	{
		id: 2,
		product_name: "Apple Watch Seris 8",
		price: 18000,
		sale: "12%",
		imager: "product-1.png",
		top_rated: 1,
		quantity: 1,
	},
	{
		id: 3,
		product_name: "xe tang",
		price: 150000,
		sale: "14%",
		imager: "product-1.png",
		top_rated: 1,
		quantity: 1,
	},
	{
		id: 4,
		product_name: "Iphone pro 12",
		price: 200000,
		sale: "12%",
		imager: "product-3.png",
		top_rated: 1,
		quantity: 1,
	},
	{
		id: 5,
		product_name: "Inphone 13 pro max",
		price: 300000,
		sale: "12%",
		top_rated: 1,
		imager: "product-3.png",
		quantity: 1,
	},
	{
		id: 6,
		product_name: "Apple Watch Series 8",
		price: 800000,
		sale: "12%",
		imager: "product-3.png",
		top_rated: 1,
		quantity: 1,
	},
];
